Feat/server generator parser
get-Pork-Belly/Webserv pull request #39
Opened 2020-10-14 09:48 UTC by simian114

서버블록과 로케이션 블록 파서 부분을 수정했습니다.

기존에는 하나의 서버에 여러 개의 로케이션 블록 내용이 들어가지 못했었습니다.

문제는 로케이션의 정보들을 저장할 변수가 없었기 떄문이었습니다.

따라서 로케이션의 정보들을 갖고 있을 변수를 하나 만들었습니다. 아래와 같습니다.
`std::map<std::string, std::map<std::string, std::string> > locations`

이 변경으로 인해 `Server` 의 생성자를 호출할 때 `Server(std::map<std::string, std::string> server_config)`에서
`Server(std::map<std::string, std::string> server_config, std::map<std::string, std::map<std::string, std::string> > locations )`로 수정이 필요해 보입니다.

그리고 http 부분의 파서는 아직 구현하지 않았습니다. 이 다음으로 구현하고 버그 픽스 진행하겠습니다.

2020-10-14 10:20 UTC, humblEgo requested changes

2020-10-14 10:20 UTC, humblEgo commented on srcs/ServerGenerator.cpp
> +            std::cout << "===============================\n\n" << std::endl;
테스트케이스와 merge할 실제코드간의 분리가 필요해보입니다!

2020-10-14 10:22 UTC, humblEgo commented on srcs/ServerGenerator.cpp
> +    std::vector<std::string> lines(100);
lines안에 100이 있는데 이는 무엇을 뜻하나요?

2020-10-14 10:24 UTC, humblEgo commented on srcs/ServerGenerator.cpp
> +            this->_configfile_lines.push_back(std::string(trimmed));
두번 생성자가 호출될까봐 걱정되는데, push_back에 객체를 생성하며 인자를 넘기는 것이 필수인지 확인부탁드립니다.

2020-10-14 10:28 UTC, humblEgo commented on srcs/ServerGenerator.cpp
> +        }
index처럼 key 값에 대응되는 value가 다수일 경우의 처리는 이후에 하신다는 점 확인받았습니다.

2020-10-14 10:36 UTC, humblEgo commented on srcs/ServerGenerator.cpp
> +            // servers.push_back(new Server(_server_config, _locations));
_locations는 멤버변수가 아닌데 멤버변수 형식을 따르고 있습니다. 변경 필요합니다.
그리고 멤버변수는 `this->_server_config`처럼 this를 붙여주세요!
by sanam, iwoo, yohlee

2020-10-14 10:38 UTC, l-yohai commented on srcs/ServerGenerator.cpp
> +        location_config["root"] = server_config["root"];
index와 root의 등장 위치 때문에 수정이 필요하다고 말씀하셨습니다. -by Sanam

2020-10-15 01:24 UTC, simian114 commented on srcs/ServerGenerator.cpp
> +    std::vector<std::string> lines(100);
100이 들어가 있는건 디버깅 과정에서 어떻게 동작하는지 확인하기 위함이었습니다. (100) 부분 수정 했습니다.

2020-10-15 01:29 UTC, simian114 commented on srcs/ServerGenerator.cpp
> +            this->_configfile_lines.push_back(std::string(trimmed));
[레퍼런스](https://en.cppreference.com/w/cpp/container/vector/push_back) 확인 결과 인자로 들어오는 값은 `복사`가 된다고 합니다. 따라서 `std::string()`으로 인자를 넣어주면 말씀하신대로 디폴트 생성자, 복사 생성자 두 번 호출되기 때문에 코드가 불필요하게 길어진것 같습니다.

2020-10-15 01:30 UTC, simian114 commented on srcs/ServerGenerator.cpp
> +            // servers.push_back(new Server(_server_config, _locations));
넵! 이 변수 말고도 `_server_config` 또한 언더바로 이름이 시작하는걸 확인하고 수정했습니다.

2020-10-15 09:45 UTC, closed without merging