Feat/request parser
get-Pork-Belly/Webserv pull request #46
Opened 2020-10-17 23:23 UTC by l-yohai

Request Parser 구현 완료했습니다.

변경사항:
- 1) 멤버변수/함수 이름 사이에 request를 추가
- 2) _request_headers 의 자료형을 std::vector<std::map<std::string, std::string>>에서 std::map<std::string, std::string> 으로 변경

명세서에 반영해놓았습니다.

getLine 함수를 이용하여 \r\n 기준으로 한 문장씩 읽고, request_line의 경우 공백을 기준으로 split, request_headers의 경우 \r\n과 : 기준으로 split 하였습니다.

아래 테스트 결과 첨부합니다.

아직 코드들이 대체로 깔끔하진 않고 모듈화되지 않은 부분들도 있습니다. 이 부분들은 valid check 를 진행하면서 많은 부분들이 변경될 수 있기 때문에, 세부적인 구현들 이후에 수정할 예정입니다.

```C
std::string req = 
"OPTION / HTTP/1.1\r\n
Host: 127.0.0.1:8080\r\n
User-Agent: Mozilla/5.0 (Macintosh;) Firefox/51.0\r\n
Accept: text/html\r\n
Accept-Language: en-US\r\n
Accept-Encoding: gzip\r\n
Connection: keep-alive\r\n
Content-Type: multipart/form-data\r\n
Content-Length: 345\r\n
\r\n
HelloWorld, everybody, buddy, whatsup\r\n";
```

```
============================= result =============================
method: OPTION
uri: /
version: HTTP/1.1
key: Accept
value: text/html
key: Accept-Encoding
value: gzip
key: Accept-Language
value: en-US
key: Connection
value: keep-alive
key: Content-Length
value: 345
key: Content-Type
value: multipart/form-data
key: Host
value: 127.0.0.1:8080
key: User-Agent
value: Mozilla/5.0 (Macintosh;) Firefox/51.0
body: HelloWorld, everybody, buddy, whatsup
```

2020-10-18 03:31 UTC, humblEgo reviewed
수고많으셨습니다! 제가 잠시 나갔다와야해서 리뷰를 마치진 못했는데, 우선 리뷰한 부분만 남겨드려요~!

2020-10-18 03:31 UTC, humblEgo commented on srcs/Request.cpp
> +    }
두가지 의문이 있습니다. 확인 부탁드립니다~!

1. `delimeter find에 실패했다는 것`을 `req_message가 empty`인 것으로 판단할 수 없을 것 같습니다. 혹시 제가 잘못 생각했을까요?
- 현재 getline 함수를 보면 delimeter find에 실패하면 'lines'를 그대로 반환하는 상태입니다. 
- 따라서 `lines가 empty가 아닌데 delimeter find를 실패하는 케이스`에는 `req_message가 empty인 것 == delimeter find에 실패했다는 것`가 동일하지 않을 것 같습니다.

2020-10-18 03:31 UTC, humblEgo commented on srcs/Request.cpp
> +    }
2. request 받고 response 만들어 보내는 flow에서는 throw를 쓰지 않고 bool 값으로 에러여부를 반환하기로 했었는데, 반영이 되지 않은 것 같습니다. 혹시 커뮤니케이션에서 오해가 있었나용?ㅠ
- 성능저하가 우려됩니다. throw문 안에서 except가 발생하는 경우엔 try-catch문을 쓴 경우보다 17배 이상의 overhead가 발생하기 때문입니다.

2020-10-18 03:31 UTC, simian114 requested changes
요한님 고생 많으셨습니다! 다만 함수의 인자로 참조를 넣어줘야 하는 경우와 메써드 호출할 때 this 포인터를 사용하지 않고 스코프로 호출하는 방법은 수정이 필요해 보입니다 :)

2020-10-18 03:31 UTC, simian114 commented on srcs/Request.cpp
> +void Request::parseRequestLine(std::string req_message)
인자로 참조를 받으면 더 좋을거 같습니다!
속도가 중요한 곳인데 괜히 생성자가 한번 더 실행되면 문제가 생길수도 있을거같아요 :)

2020-10-18 03:31 UTC, simian114 commented on srcs/Request.cpp
> +        Request::setRequestHeaders(headers);
이 부분은 왜 `Request::` 처럼 스코프를 이용해서 함수호출을 하셨나요??
평소에 사용하던 문법이 아니어서 신기하기는 한데 ㅎㅎ `this`로 해도 문제가 없더라고요

2020-10-18 03:31 UTC, simian114 commented on srcs/Request.cpp
> +    if (req_message.empty())
조건문에 한줄이면 괄호는 없애주는게 좋을거같습니다! 협업규칙 포매팅란에 있는 내용입니다 👍

2020-10-18 19:35 UTC, l-yohai commented
말씀해주신 것들만 먼저 반영해서 수정해놓았습니다.

- 조건문 안에 single line 일 시 중괄호 삭제
- throw -> return ; 로 변경

getLine 함수는 함수명이랑 역할에 대해서 조금 더 생각해 보고 수정하겠습니다.

지금 진행중인 유효성 검사 부분은 작업이 pr날리기 전에 분기한 브랜치 푸시하면서 작업하겠습니다.

2020-10-19 06:35 UTC, l-yohai commented
변경하여 푸시 날렸습니다.

버전관리를 위해 Valid Check 부분은 생략하고 올렸습니다.

커멘트 달아주신 부분들 전부 수정 완료했습니다.
1. throw -> return (false) 로 변경.
2. getLine -> substr 으로 변경
3. 조건문 안에 한 줄만 있을 때 중괄호 생략

그 외 내용은 동일합니다.

2020-10-19 06:46 UTC, humblEgo commented on srcs/Request.cpp
> +bool Request::parseRequest(std::string req_message)
참조자를 받도록 수정 부탁드립니다~~! :)

2020-10-19 06:56 UTC, simian114 approved these changes
고생많으셨습니다!!!

2020-10-19 06:56 UTC, simian114 commented on srcs/Request.cpp
> +    Request::setRequestBodies(req_message);
메써드 실행은 this 포인터로 하는게 좋을거 같습니다!

2020-10-19 06:56 UTC, simian114 commented on srcs/Request.cpp
> +    {
우리의 협업 규칙에 따르면 싱글라인은 괄호를 생략합니다 !!! :)

2020-10-19 06:56 UTC, merged