Feat/request valid check
get-Pork-Belly/Webserv pull request #49
Opened 2020-10-19 07:31 UTC by l-yohai

Request Valid Check에 대한 일정 부분들을 담았습니다.

진행한 유효성 검사입니다.

1. Request Line이 유효한지 검사
    - Request Method가 유효한지 검사
    - Request URI가 유효한지 검사 // <- 이 부분에 대해서는 더 조사가 필요합니다.
    - Request Version이 유효한지 검사 // <- 이 부분 역시 확장될 수 있는 HTTP 버전을 받아야할 지 논의가 필요해보입니다.
2. Request Header 검사
    - 파싱된 headers map의 key와 value가 비어있는지 검사
    - key에 공백이 포함되어 있는지 검사
    - RequestHeaderFields가 처리해야 할 헤더필드인지 검사 (서브젝트에 나와있는 헤더들과 compare 한 후 없는 헤더가 포함되어 있으면 false를 리턴하도록 처리했지만, sanam님께서는 이 부분이 필요없을 것 같다는 의견을 주셨습니다. 서브젝트에 요구되지 않은 헤더가 있을 때 어떻게 처리해야 할 지 논의가 필요해 보입니다.)
    - 헤더 key에 중복이 있는지 검사

+++

추가해야할 것들
- Request Headers 를 담아내는 map의 value에 대한 유효성 검사
- 오류가 나왔을 시 반환해야 할 status code
- Request Bodies 에 대한 유효성검사 (entity가 들어왔을 때 혹은 transfer-type이 chunked일 때 혹은 authorization이 필요할 때)

추가해야 할 부분에 대해서는 RFC를 뜯어보다시피 해야 하는 규모가 큰 작업들이기 때문에, 어느정도 구현이 된 이후에 추가적으로 작업해 보이는 것이 좋아보이기 때문에 PR 날리게 되었습니다.

2020-10-19 07:56 UTC, humblEgo reviewed
세세한 설명 덕에 리뷰가 쉬웠네요. 발견한 수정사항 반영하여 다시 push 하신 후 말씀주세요~!! :)

2020-10-19 07:56 UTC, humblEgo commented on srcs/Request.cpp
>          return (true);
대화통해 1.0 버전도 처리필요하다는 것 확인했습니다. TODO에 1.0 버전도 처리필요함을 남겨주세요!

2020-10-19 07:56 UTC, humblEgo commented on srcs/Request.cpp
>      else
167~176 line의 경우, `return (false);`로 대체하시면 될 것 같습니다.

2020-10-19 07:56 UTC, humblEgo commented on srcs/Request.cpp
>          headers[key] = value;
의미가 없어진 코드임을 확인했고, 삭제 요망합니다!

2020-10-19 07:56 UTC, humblEgo commented on srcs/Request.cpp
>  }
필요없어진 함수임을 확인헀습니다. 삭제요망합니다!

2020-10-19 07:56 UTC, humblEgo commented on srcs/Request.cpp
>      else
188~191 line 또한 `return (false);` 로 대체 부탁드립니다!

2020-10-19 07:57 UTC, simian114 requested changes
고생하셨습니다! 다만 조금 다듬을 필요가 있어보입니다 👍

2020-10-19 07:57 UTC, simian114 commented on srcs/Request.cpp
> +bool Request::isValidRequestHeaderFields(std::string& key)
이 부분이 만약 있다고 하면 여기에 없는 헤더가 들어있는 리퀘스트가 들어오면 전부 false처리하는거 같은데, 이렇게 되면 웹서버의 기능을 전혀 하지 못한다고 생각합니다. 나중에 HTTP 1.1에 해당하는 모든 헤더들을 넣을 필요가 있어 보입니다.

2020-10-21 07:59 UTC, simian114 approved these changes
고생하셨습니다 👍 👍

2020-10-21 08:51 UTC, closed without merging